<?php

namespace AppBundle\Repository;

/**
 * AnswerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */

class AnswerRepository extends \Doctrine\ORM\EntityRepository
{
    public function getSurveyAnswers($idSurvey)
    {
        $query = $this->createQueryBuilder("a");
        $query
            ->select('COUNT(a.answerId),e.choice,e.id,a.answerDate')
            ->leftJoin("a.answerId",'e')->addSelect('e.choice')
            ->where('e.Survey = :survey')
            ->groupBy("e.choice")
            ->setParameter('survey',$idSurvey);

        return $query->getQuery()->getResult();
    }

    public function getAnswersByDate($idSurvey)
    {
        $query = $this->createQueryBuilder("a");
        $query
            ->select('COUNT(a.answerId),e.choice,e.id,a.answerDate')
            ->leftJoin("a.answerId",'e')->addSelect('e.choice')
            ->where('e.Survey = :survey')
            ->groupBy("e.choice,a.answerDate")
            ->orderBy('a.answerDate,e.choice')
            ->setParameter('survey',$idSurvey);

        return $query->getQuery()->getResult();

    }


    public function getAnswersNumber($idSurvey)
    {
        $query2 = $this->createQueryBuilder("a");
        $query2
            ->select('COUNT(a.answerId)')
            ->where('a.lastSurvey = :surv')
            ->setParameter('surv',$idSurvey);

        return $query2->getQuery()->getResult();
    }

    public function getDatesOneSurvey($idSurvey)
    {
        $query = $this->createQueryBuilder("a");
        $query
            ->select('a.answerDate')
            ->where('a.lastSurvey = :surv')
            ->groupBy('a.answerDate')
            ->setParameter('surv',$idSurvey);

        return $query->getQuery()->getResult();
    }
}
?>
<!--SELECT count(*), choice.choice FROM answer LEFT JOIN choice ON answer.answer_id_id = choice.id
GROUP BY choice ;-->
