choice_index:
    path:     /
    defaults: { _controller: "AppBundle:Choice:index" }
    methods:  GET

choice_show:
    path:     /{id}/show
    defaults: { _controller: "AppBundle:Choice:show" }
    methods:  GET

choice_new:
    path:     /new
    defaults: { _controller: "AppBundle:Choice:new" }
    methods:  [GET, POST]

choice_edit:
    path:     /{id}/edit
    defaults: { _controller: "AppBundle:Choice:edit" }
    methods:  [GET, POST]

choice_delete:
    path:     /{id}/delete
    defaults: { _controller: "AppBundle:Choice:delete" }
    methods:  DELETE
